[build]
  command = "git submodule update --init --recursive && hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.160.1"
  NODE_VERSION = "18"
  HUGO_ENV = "production"
